### ISSUE TITLE
Thunderbird configuration for MyMetronet.NET accounts

### ISSUE THREAD

**Issue by Barry-IA** [nasqueron/infra-autoconfig#1]
Hi! 
I'm probably in the wrong area but just trying to add some information for autoconfiguring Thunderbird e-mail when a user has a MyMetronet.NET address.   Thunderbird was unable to find the server.  The server hostname for incoming and outgoing mail is mail.powerxmail.com ==>
![image](https://user-images.githubusercontent.com/45851634/87864509-cb9d8c80-c92e-11ea-8e06-43764e5b889d.png)

Hope that helps other subscribers.

**Comment by dereckson** [comment]
Hi,

Indeed, you're ^^

But, as you're lost here, you can use our config as an example of what you need to do.

You need to create a file like
https://github.com/nasqueron/infra-autoconfig/blob/master/mail/config-v1.1.xml

and host it at https://autoconfig.MyMetronet.NET/mail/config-v1.1.xml

If you want to do something dynamic to personalise the document by user,  Thunderbird will actually query https://autoconfig.MyMetronet.NET/mail/config-v1.1.xml?emailaddress=someuser@MyMetronet.NET
